name: Version Plugin Reference

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone elastic/docs-tools
        uses: actions/checkout@v2
        with:
          repository: elastic/docs-tools
          path: docs-tools
          fetch-depth: 1
      - name: Setup git user
        working-directory: ./docs-tools
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
      - run: bundle install
        working-directory: ./docs-tools
      - name: Generate plugin versions
        working-directory: ./docs-tools
        env:
          JRUBY_OPTS: "-J-Xmx4g"
        run: ./ci/generate_versioned_docs.sh
